[package]
name = "tudo-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[[bin]]
name = "tudo"
path = "src/tudo.rs"

[dependencies]

#cli
clap = { version = "4", features = ["derive", "env", "unicode", "wrap_help"] }
color-eyre = "0.6.2"
dotenvy = "0.15.7"
eyre = "0.6.8"

