[package]
name = "tudo-executor"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
# internal
tudo-primitives = { workspace = true }
ethers = { workspace = true }

# misc
async-trait = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
derive_builder = "0.12.0"

[dev-dependencies]
claims = { version = "0.7" }

